spring:
  config:
    import: optional:dotenv
  application:
    name: spring-ai-demo
  ai:
    vectorstore:
      vector-store-path: data/vector-store.json
      documents-to-load:
        - classpath:top_popular_movies.csv
    ollama:
      base-url: http://localhost:11434
      chat:
        model: tinyllama:latest
        options:
          temperature: 0.0
